table fact_tv
	lineageTag: dcc146f8-db0d-4470-af50-eed87393b28a

	measure tv_count = ```
			
			    if(
			        COUNTROWS(fact_tv)==BLANK(),
			        0,
			        COUNTROWS(fact_tv)
			    )
			
			
			```
		formatString: 0
		lineageTag: 6ccf1c73-e91c-415c-b765-39cd8dd54a58

	column TV_ID
		dataType: int64
		formatString: 0
		lineageTag: d89fbf23-7b87-4520-a418-11f04b38fdc9
		summarizeBy: none
		sourceColumn: TV_ID

		annotation SummarizationSetBy = Automatic

	column First_Air_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4a8d3733-b145-4a84-bc15-30033e9e0372
		summarizeBy: none
		sourceColumn: First_Air_Date

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 813dca59-0830-48eb-9247-780f07f06146
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Origin_Country
		dataType: string
		lineageTag: 27057120-eda6-4e47-92f1-606cfead316d
		summarizeBy: none
		sourceColumn: Origin_Country

		annotation SummarizationSetBy = Automatic

	column Original_Language
		dataType: string
		lineageTag: 0fa15ff3-8b91-4676-8c98-15efae624e0e
		summarizeBy: none
		sourceColumn: Original_Language

		annotation SummarizationSetBy = Automatic

	column Original_Name
		dataType: string
		lineageTag: 4c45ce76-192b-4a51-baa4-d138e2cbb8b2
		summarizeBy: none
		sourceColumn: Original_Name

		annotation SummarizationSetBy = Automatic

	column Overview
		dataType: string
		lineageTag: bb677580-f88c-43f8-b779-ceb2c30cdb57
		summarizeBy: none
		sourceColumn: Overview

		annotation SummarizationSetBy = Automatic

	column Popularity
		dataType: double
		lineageTag: f281345a-9015-4f12-b915-18cb78554210
		summarizeBy: none
		sourceColumn: Popularity

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Vote_Average
		dataType: double
		lineageTag: df77ddd4-d24a-47d6-9747-b42963664dbb
		summarizeBy: none
		sourceColumn: Vote_Average

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"fact_tv","TableItemName":"Vote_Average (bins)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column Vote_Count
		dataType: double
		lineageTag: d9b134cf-9c91-4767-b7f4-1098a9d8e8d8
		summarizeBy: none
		sourceColumn: Vote_Count

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column episode_run_time
		dataType: int64
		formatString: 0
		lineageTag: 8cf38d71-5859-459d-a747-f353661d9d05
		summarizeBy: none
		sourceColumn: episode_run_time

		annotation SummarizationSetBy = User

	column 'Vote_Average (bins)' = ```
			VAR __Count = 10
			
			VAR __Min = MIN('fact_tv'[Vote_Average])
			
			VAR __Max = MAX('fact_tv'[Vote_Average])
			
			VAR __Difference = (__Max - __Min)
			
			VAR __Size = IF(__Difference > 0, __Difference / __Count, 1)
			
			VAR __BinNumber = 
				IF(
					ISBLANK('fact_tv'[Vote_Average]),
					BLANK(),
					ROUNDDOWN(('fact_tv'[Vote_Average] - __Min) / __Size, 0)
				)
			
			RETURN
				IF(
					ISBLANK('fact_tv'[Vote_Average]),
					BLANK(),
					__Min + (MIN(__BinNumber, __Count - 1) * __Size)
				)
			```
		lineageTag: 5081f9a0-eac0-42bd-8306-b020a0ed85b7
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "fact_tv"
				          }
				        },
				        "Property": "Vote_Average"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"f","Entity":"fact_tv"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"Vote_Average"}}],"BinItem":{"Expression":{"Member":{"Expression":{"Discretize":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"Vote_Average"}},"Count":10}},"Member":"Min"}}}}

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Adult
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2833e148-d3a5-4109-9fee-d0459aab0119
		summarizeBy: none
		sourceColumn: Adult

		annotation SummarizationSetBy = Automatic

	column Genres
		dataType: string
		lineageTag: 5a6f8eb3-d7a9-4108-8a07-05f39b7d5773
		summarizeBy: none
		sourceColumn: Genres

		annotation SummarizationSetBy = Automatic

	column In_Production
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ce64aad3-8f83-4e0b-821b-fff445220ede
		summarizeBy: none
		sourceColumn: In_Production

		annotation SummarizationSetBy = Automatic

	column Last_Air_Date
		dataType: string
		lineageTag: 6b86217f-72d1-442d-9041-6e375861e9eb
		summarizeBy: none
		sourceColumn: Last_Air_Date

		annotation SummarizationSetBy = Automatic

	column Number_Of_Episodes
		dataType: int64
		formatString: 0
		lineageTag: 28767b00-9e0f-415b-ad9c-c59a8e401255
		summarizeBy: sum
		sourceColumn: Number_Of_Episodes

		annotation SummarizationSetBy = Automatic

	column Number_Of_Seasons
		dataType: int64
		formatString: 0
		lineageTag: 69295213-896c-4494-9538-32e7808368cd
		summarizeBy: sum
		sourceColumn: Number_Of_Seasons

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 3ff824de-ea03-4429-a0de-f9bea70442a5
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: e2894059-2635-488c-ba4f-cdba284e8c35
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	partition fact_tv = m
		mode: import
		source =
				let
				    Source = Sql.Database("myfreesqldbserver66.database.windows.net", "TMDB", [Query="select * from [dbo].[fact_tv] where First_Air_Date < getdate()"]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Backdrop_Path", "Poster_Path"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

